Feature/add generator for submodels
bci-oss/sds-sdk pull request #2
Opened 2023-03-02 13:24 UTC by andreas-schilling

Implement https://github.com/eclipse-esmf/esmf-sdk/issues/280

2023-03-20 06:24 UTC, atextor requested changes

2023-03-20 06:24 UTC, atextor commented on core/sds-aspect-model-aas-generator/src/main/java/io/openmanufacturing/sds/aspectmodel/aas/AspectModelAASGenerator.java
> +                           .map( aspectWithData -> {
Indentation looks wrong here, the dots should not be aligned. Please check/adjust format across all files.

2023-03-20 06:24 UTC, atextor commented on core/sds-aspect-model-aas-generator/src/main/java/io/openmanufacturing/sds/aspectmodel/aas/DefaultPropertyMapper.java
> +   public Property mapToAasProperty( Type type, io.openmanufacturing.sds.metamodel.Property property, Context context ) {
Please adjust Save Actions; arguments should be final

2023-03-29 09:41 UTC, andreas-schilling commented on core/sds-aspect-model-aas-generator/src/main/java/io/openmanufacturing/sds/aspectmodel/aas/AspectModelAASGenerator.java
> +                           .map( aspectWithData -> {
done.

2023-03-29 09:41 UTC, andreas-schilling commented on core/sds-aspect-model-aas-generator/src/main/java/io/openmanufacturing/sds/aspectmodel/aas/DefaultPropertyMapper.java
> +   public Property mapToAasProperty( Type type, io.openmanufacturing.sds.metamodel.Property property, Context context ) {
done.

2023-03-29 11:55 UTC, atextor approved these changes

2023-04-17 11:29 UTC, atextor approved these changes

2023-05-08 13:03 UTC, atextor approved these changes

2023-06-12 13:57 UTC, closed without merging

2023-06-12 13:58 UTC, andreas-schilling commented
Created new PR that directly targets the upstream repo. See https://github.com/eclipse-esmf/esmf-sdk/pull/364